import type { BuiltinModelRecord } from '../types'
import { model, textCapabilities, visionCapabilities, imageCapabilities, videoCapabilities, toggleThinking } from '../helpers'

export const DOUBAO: readonly BuiltinModelRecord[] = [
  model('doubao', 'doubao-seed-evolving', '豆包 Seed Evolving', {
    capabilities: visionCapabilities({
      thinking: true,
      tools: true,
      structuredOutput: true,
      caching: true,
    }),
    contextWindow: 1_048_576,
    maxOutputTokens: 262_144,
    thinkingConfig: toggleThinking('thinking.type'),
    verificationStatus: 'official-api',
  }),
  model('doubao', 'doubao-seed-2-1-pro-260628', '豆包 Seed 2.1 Pro', {
    capabilities: visionCapabilities({
      thinking: true,
      tools: true,
      structuredOutput: true,
      caching: true,
    }),
    contextWindow: 262_144,
    maxOutputTokens: 262_144,
    thinkingConfig: toggleThinking('thinking.type'),
    aliases: ['doubao-seed-2.1-pro', 'doubao-seed-2-1-pro'],
    pricingModelId: 'doubao-seed-2.1-pro',
    verificationStatus: 'official-api',
  }),
  model('doubao', 'doubao-seed-2-1-turbo-260628', '豆包 Seed 2.1 Turbo', {
    capabilities: visionCapabilities({
      thinking: true,
      tools: true,
      structuredOutput: true,
      caching: true,
    }),
    contextWindow: 262_144,
    maxOutputTokens: 262_144,
    thinkingConfig: toggleThinking('thinking.type'),
    aliases: ['doubao-seed-2.1-turbo', 'doubao-seed-2-1-turbo'],
    pricingModelId: 'doubao-seed-2.1-turbo',
    verificationStatus: 'official-api',
  }),
  model('doubao', 'doubao-seed-2-0-pro-260215', '豆包 Seed 2.0 Pro', {
    capabilities: visionCapabilities({
      thinking: true,
      tools: true,
      structuredOutput: true,
      caching: true,
    }),
    contextWindow: 262_144,
    maxOutputTokens: 131_072,
    thinkingConfig: toggleThinking('thinking.type'),
    aliases: ['doubao-seed-2.0-pro', 'doubao-seed-2-0-pro'],
    pricingModelId: 'doubao-seed-2.0-pro',
    verificationStatus: 'official-api',
  }),
  model('doubao', 'doubao-seed-2-0-lite-260428', '豆包 Seed 2.0 Lite', {
    capabilities: visionCapabilities({
      thinking: true,
      tools: true,
      structuredOutput: true,
      caching: true,
    }),
    contextWindow: 262_144,
    maxOutputTokens: 131_072,
    thinkingConfig: toggleThinking('thinking.type'),
    aliases: ['doubao-seed-2.0-lite', 'doubao-seed-2-0-lite', 'doubao-seed-2-0-lite-260215'],
    pricingModelId: 'doubao-seed-2.0-lite',
    verificationStatus: 'official-api',
  }),
  model('doubao', 'doubao-seed-2-0-mini-260428', '豆包 Seed 2.0 Mini', {
    capabilities: visionCapabilities({
      thinking: true,
      tools: true,
      structuredOutput: true,
      caching: true,
    }),
    contextWindow: 262_144,
    maxOutputTokens: 131_072,
    thinkingConfig: toggleThinking('thinking.type'),
    aliases: ['doubao-seed-2.0-mini', 'doubao-seed-2-0-mini', 'doubao-seed-2-0-mini-260215'],
    pricingModelId: 'doubao-seed-2.0-mini',
    verificationStatus: 'official-api',
  }),
  model('doubao', 'doubao-seed-2-0-code-preview-260215', '豆包 Seed 2.0 Code Preview', {
    capabilities: visionCapabilities({
      thinking: true,
      tools: true,
      caching: true,
    }),
    contextWindow: 262_144,
    maxOutputTokens: 131_072,
    thinkingConfig: toggleThinking('thinking.type'),
    aliases: ['doubao-seed-2.0-code', 'doubao-seed-2-0-code'],
    pricingModelId: 'doubao-seed-2.0-code',
    verificationStatus: 'official-api',
  }),
  model('doubao', 'doubao-seed-character-260628', '豆包 Seed Character', {
    capabilities: visionCapabilities({
      thinking: true,
      tools: true,
      structuredOutput: true,
      caching: true,
    }),
    contextWindow: 131_072,
    maxOutputTokens: 32_768,
    thinkingConfig: toggleThinking('thinking.type'),
    aliases: ['doubao-seed-character'],
    pricingModelId: 'doubao-seed-character',
    verificationStatus: 'official-api',
  }),
  model('doubao', 'doubao-seed-code-preview-251028', '豆包 Seed Code Preview', {
    capabilities: visionCapabilities({
      thinking: true,
      tools: true,
      caching: true,
    }),
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    thinkingConfig: toggleThinking('thinking.type'),
    aliases: ['doubao-seed-code'],
    pricingModelId: 'doubao-seed-code',
    verificationStatus: 'official-api',
  }),
  model('doubao', 'doubao-seed-1-6-flash-250828', '豆包 Seed 1.6 Flash', {
    capabilities: visionCapabilities({
      thinking: true,
      tools: true,
      structuredOutput: true,
      caching: true,
    }),
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    thinkingConfig: toggleThinking('thinking.type'),
    aliases: ['doubao-seed-1.6-flash', 'doubao-seed-1-6-flash', 'doubao-seed-1-6-flash-250615'],
    pricingModelId: 'doubao-seed-1.6-flash',
    verificationStatus: 'official-api',
  }),
  model('doubao', 'doubao-seed-1-6-vision-250815', '豆包 Seed 1.6 Vision', {
    capabilities: visionCapabilities({
      thinking: true,
      tools: true,
      structuredOutput: true,
      caching: true,
    }),
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    thinkingConfig: toggleThinking('thinking.type'),
    aliases: ['doubao-seed-1.6-vision', 'doubao-seed-1-6-vision'],
    pricingModelId: 'doubao-seed-1.6-vision',
    verificationStatus: 'official-api',
  }),
  model('doubao', 'doubao-1-5-pro-32k-250115', '豆包 1.5 Pro 32K', {
    capabilities: textCapabilities({ tools: true, caching: true }),
    contextWindow: 131_072,
    maxOutputTokens: 16_384,
    aliases: ['doubao-1.5-pro-32k', 'doubao-1-5-pro-32k'],
    pricingModelId: 'doubao-1.5-pro-32k',
    verificationStatus: 'official-api',
  }),
  model('doubao', 'doubao-1-5-lite-32k-250115', '豆包 1.5 Lite 32K', {
    capabilities: textCapabilities({ tools: true, caching: true }),
    contextWindow: 32_768,
    maxOutputTokens: 12_288,
    aliases: ['doubao-1.5-lite-32k', 'doubao-1-5-lite-32k'],
    pricingModelId: 'doubao-1.5-lite-32k',
    verificationStatus: 'official-api',
  }),
  model('doubao', 'doubao-1.5-vision-pro', '豆包 1.5 Vision Pro', {
    capabilities: visionCapabilities(),
    pricingModelId: 'doubao-1.5-vision-pro',
    verificationStatus: 'official-api',
  }),
  model('doubao', 'doubao-seed-translation-250915', '豆包 Seed Translation', {
    capabilities: textCapabilities({ tools: false }),
    contextWindow: 4_096,
    maxOutputTokens: 3_072,
    aliases: ['doubao-seed-translation'],
    pricingModelId: 'doubao-seed-translation',
    verificationStatus: 'official-api',
  }),
  model('doubao', 'doubao-seed-1-6', '豆包 Seed 1.6', {
    capabilities: visionCapabilities({
      thinking: true,
      tools: true,
      structuredOutput: true,
    }),
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    thinkingConfig: toggleThinking('thinking.type'),
  }),
  model('doubao', 'doubao-seedream-4-0', 'Seedream 4.0', {
    modality: 'image',
    capabilities: imageCapabilities(),
    aliases: ['seedream-4.0'],
  }),
  model('doubao', 'doubao-seedance-1-0-pro', 'Seedance 1.0 Pro', {
    modality: 'video',
    capabilities: videoCapabilities(),
    aliases: ['seedance-1.0-pro'],
  }),
]
