import type { BuiltinModelRecord } from '../types'
import type { ModelCapabilities } from '../../provider'
import { model, visionCapabilities, effortThinking, source } from '../helpers'

const geminiStandardCapabilities = (fileInput = true): ModelCapabilities =>
  visionCapabilities({
    thinking: true,
    fileInput,
    videoInput: true,
    audioInput: true,
    tools: true,
    caching: true,
    webSearch: true,
    structuredOutput: true,
    streaming: true,
    batch: true,
  })

export const GOOGLE: readonly BuiltinModelRecord[] = [
  model('google', 'gemini-3.8-flash', 'Gemini 3.8 Flash', {
    capabilities: geminiStandardCapabilities(),
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    thinkingConfig: effortThinking('reasoning_effort', 'medium'),
    reasoningEfforts: ['low', 'medium', 'high'],
    source: source('https://ai.google.dev/gemini-api/docs/models/gemini-3.8-flash'),
    verificationStatus: 'official-api',
  }),
  model('google', 'gemini-3.7-flash', 'Gemini 3.7 Flash', {
    capabilities: geminiStandardCapabilities(),
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    thinkingConfig: effortThinking('reasoning_effort', 'medium'),
    reasoningEfforts: ['low', 'medium', 'high'],
    source: source('https://ai.google.dev/gemini-api/docs/models/gemini-3.7-flash'),
    verificationStatus: 'official-api',
  }),
  model('google', 'gemini-3.6-flash', 'Gemini 3.6 Flash', {
    capabilities: geminiStandardCapabilities(),
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    thinkingConfig: effortThinking('reasoning_effort', 'medium'),
    reasoningEfforts: ['minimal', 'low', 'medium', 'high'],
    source: source('https://ai.google.dev/gemini-api/docs/models/gemini-3.6-flash'),
    verificationStatus: 'official-api',
  }),
  model('google', 'gemini-3.5-flash', 'Gemini 3.5 Flash', {
    capabilities: geminiStandardCapabilities(),
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    thinkingConfig: effortThinking('reasoning_effort', 'medium'),
    reasoningEfforts: ['minimal', 'low', 'medium', 'high'],
    source: source('https://ai.google.dev/gemini-api/docs/models/gemini-3.5-flash'),
    verificationStatus: 'official-api',
  }),
  model('google', 'gemini-3.5-flash-lite', 'Gemini 3.5 Flash-Lite', {
    capabilities: geminiStandardCapabilities(),
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    thinkingConfig: effortThinking('reasoning_effort', 'minimal'),
    reasoningEfforts: ['minimal', 'low', 'medium', 'high'],
    source: source('https://ai.google.dev/gemini-api/docs/models/gemini-3.5-flash-lite'),
    verificationStatus: 'official-api',
  }),
  model('google', 'gemini-3.1-pro-preview', 'Gemini 3.1 Pro Preview', {
    capabilities: geminiStandardCapabilities(),
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    thinkingConfig: effortThinking('reasoning_effort', 'high'),
    reasoningEfforts: ['low', 'medium', 'high'],
    aliases: ['gemini-3.1-pro'],
    source: source('https://ai.google.dev/gemini-api/docs/models/gemini-3.1-pro-preview'),
    verificationStatus: 'official-api',
  }),
  model('google', 'gemini-3.1-flash-lite', 'Gemini 3.1 Flash-Lite', {
    capabilities: geminiStandardCapabilities(),
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    thinkingConfig: effortThinking('reasoning_effort', 'minimal'),
    reasoningEfforts: ['minimal', 'low', 'medium', 'high'],
    source: source('https://ai.google.dev/gemini-api/docs/models/gemini-3.1-flash-lite'),
    verificationStatus: 'official-api',
  }),
  model('google', 'gemini-3-flash-preview', 'Gemini 3 Flash Preview', {
    capabilities: geminiStandardCapabilities(),
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    thinkingConfig: effortThinking('reasoning_effort', 'high'),
    reasoningEfforts: ['minimal', 'low', 'medium', 'high'],
    source: source('https://ai.google.dev/gemini-api/docs/models/gemini-3-flash-preview'),
    verificationStatus: 'official-api',
  }),
  model('google', 'gemini-2.5-pro', 'Gemini 2.5 Pro', {
    capabilities: geminiStandardCapabilities(),
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    thinkingConfig: effortThinking('reasoning_effort', 'medium'),
    reasoningEfforts: ['low', 'medium', 'high'],
    source: source('https://ai.google.dev/gemini-api/docs/models/gemini-2.5-pro'),
    verificationStatus: 'official-api',
  }),
  model('google', 'gemini-2.5-flash', 'Gemini 2.5 Flash', {
    capabilities: geminiStandardCapabilities(),
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    thinkingConfig: effortThinking('reasoning_effort', 'medium'),
    reasoningEfforts: ['none', 'low', 'medium', 'high'],
    source: source('https://ai.google.dev/gemini-api/docs/models/gemini-2.5-flash'),
    verificationStatus: 'official-api',
  }),
  model('google', 'gemini-2.5-flash-lite', 'Gemini 2.5 Flash-Lite', {
    capabilities: geminiStandardCapabilities(),
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    thinkingConfig: {
      mode: 'effort',
      defaultEnabled: false,
      defaultEffort: 'medium',
      parameterPath: 'reasoning_effort',
    },
    reasoningEfforts: ['none', 'low', 'medium', 'high'],
    source: source('https://ai.google.dev/gemini-api/docs/models/gemini-2.5-flash-lite'),
    verificationStatus: 'official-api',
  }),
  model('google', 'gemma-3-27b-it', 'Gemma 3 27B', {
    capabilities: visionCapabilities({ tools: false }),
    source: source('https://ai.google.dev/gemma/docs/core/model_card_3'),
    verificationStatus: 'official-model-card',
  }),
  model('google', 'gemma-3-12b-it', 'Gemma 3 12B', {
    capabilities: visionCapabilities({ tools: false }),
    source: source('https://ai.google.dev/gemma/docs/core/model_card_3'),
    verificationStatus: 'official-model-card',
  }),
  model('google', 'gemma-3-4b-it', 'Gemma 3 4B', {
    capabilities: visionCapabilities({ tools: false }),
    source: source('https://ai.google.dev/gemma/docs/core/model_card_3'),
    verificationStatus: 'official-model-card',
  }),
]
