import type { BuiltinModelRecord } from '../types'
import { model, textCapabilities, visionCapabilities, toggleThinking, effortThinking, alwaysThinking, source } from '../helpers'

export const SENSENOVA: readonly BuiltinModelRecord[] = [
  model('sensenova', 'SenseNova-V6-5-Pro', 'SenseNova V6.5 Pro', {
    capabilities: visionCapabilities({ tools: false, videoInput: true, thinking: true, streaming: true }),
    contextWindow: 131_072,
    maxOutputTokens: 16_384,
    thinkingConfig: toggleThinking('thinking.enabled'),
    aliases: ['SenseNova-V6.5-Pro'],
    source: source('https://www.sensecore.cn/help/docs/model-as-a-service/nova/model/fusionllm/FusionLLMs'),
    verificationStatus: 'official-api',
  }),
  model('sensenova', 'SenseNova-V6-5-Turbo', 'SenseNova V6.5 Turbo', {
    capabilities: visionCapabilities({ tools: false, videoInput: true, thinking: true, streaming: true }),
    contextWindow: 131_072,
    maxOutputTokens: 16_384,
    thinkingConfig: toggleThinking('thinking.enabled'),
    aliases: ['SenseNova-V6.5-Turbo'],
    source: source('https://www.sensecore.cn/help/docs/model-as-a-service/nova/model/fusionllm/FusionLLMs'),
    verificationStatus: 'official-api',
  }),
  model('sensenova', 'SenseNova-V6-Pro', 'SenseNova V6 Pro', {
    capabilities: visionCapabilities({ tools: false, streaming: true }),
    contextWindow: 32_768,
    maxOutputTokens: 16_384,
    source: source('https://www.sensecore.cn/help/docs/model-as-a-service/nova/model/fusionllm/FusionLLMs'),
    verificationStatus: 'official-api',
  }),
  model('sensenova', 'SenseNova-V6-Turbo', 'SenseNova V6 Turbo', {
    capabilities: visionCapabilities({ tools: false, videoInput: true, streaming: true }),
    contextWindow: 32_768,
    maxOutputTokens: 16_384,
    source: source('https://www.sensecore.cn/help/docs/model-as-a-service/nova/model/fusionllm/FusionLLMs'),
    verificationStatus: 'official-api',
  }),
  model('sensenova', 'SenseNova-V6-Reasoner', 'SenseNova V6 Reasoner', {
    capabilities: visionCapabilities({ tools: false, thinking: true, streaming: true }),
    contextWindow: 32_768,
    maxOutputTokens: 16_384,
    thinkingConfig: alwaysThinking('thinking.enabled'),
    source: source('https://www.sensecore.cn/help/docs/model-as-a-service/nova/model/fusionllm/FusionLLMs'),
    verificationStatus: 'official-api',
  }),
  model('sensenova', 'SenseChat-Vision', 'SenseChat Vision', {
    capabilities: visionCapabilities({ tools: false, streaming: true }),
    contextWindow: 16_384,
    maxOutputTokens: 16_384,
    source: source('https://www.sensecore.cn/help/docs/model-as-a-service/nova/model/mllm'),
    verificationStatus: 'official-api',
  }),
  model('sensenova', 'SenseChat-Character-Pro', 'SenseChat Character Pro', {
    capabilities: textCapabilities({ tools: false }),
    contextWindow: 32_768,
    maxOutputTokens: 4_096,
    source: source('https://www.sensecore.cn/help/docs/model-as-a-service/nova/model/llm/CharacterLLM'),
    verificationStatus: 'official-api',
  }),
  model('sensenova', 'SenseChat-Character', 'SenseChat Character', {
    capabilities: textCapabilities({ tools: false }),
    contextWindow: 8_192,
    maxOutputTokens: 1_024,
    source: source('https://www.sensecore.cn/help/docs/model-as-a-service/nova/model/llm/CharacterLLM'),
    verificationStatus: 'official-api',
  }),
  model('sensenova', 'SenseChat-5', 'SenseChat 5', {
    capabilities: textCapabilities({ thinking: true, streaming: true }),
    contextWindow: 131_072,
    maxOutputTokens: 4_096,
    thinkingConfig: effortThinking('reasoning_effort'),
    reasoningEfforts: ['low', 'medium'],
    source: source('https://www.sensecore.cn/help/docs/model-as-a-service/nova/overview/compatible-mode'),
    verificationStatus: 'official-api',
  }),
  model('sensenova', 'SenseChat', 'SenseChat', {
    capabilities: textCapabilities({ tools: false, streaming: true }),
    contextWindow: 4_096,
    maxOutputTokens: 2_048,
    source: source('https://www.sensecore.cn/help/docs/model-as-a-service/nova/overview/compatible-mode'),
    verificationStatus: 'official-api',
  }),
  model('sensenova', 'SenseChat-Turbo', 'SenseChat Turbo', {
    capabilities: textCapabilities({ tools: false, streaming: true }),
    contextWindow: 32_768,
    maxOutputTokens: 2_048,
    source: source('https://www.sensecore.cn/help/docs/model-as-a-service/nova/overview/compatible-mode'),
    verificationStatus: 'official-api',
  }),
  model('sensenova', 'SenseChat-5-Cantonese', 'SenseChat 5 Cantonese', {
    capabilities: textCapabilities({ tools: false, streaming: true }),
    contextWindow: 32_768,
    maxOutputTokens: 2_048,
    source: source('https://www.sensecore.cn/help/docs/model-as-a-service/nova/overview/compatible-mode'),
    verificationStatus: 'official-api',
  }),
  model('sensenova', 'SenseChat-FunctionCall', 'SenseChat Function Call', {
    capabilities: textCapabilities({ tools: true, streaming: true }),
    contextWindow: 32_768,
    maxOutputTokens: 2_048,
    source: source('https://www.sensecore.cn/help/docs/model-as-a-service/nova/chat/ChatCompletions/FunctionCalling'),
    verificationStatus: 'official-api',
  }),
]
